services:
  redis:
    image: redis:latest
    container_name: database-redis-latest
    restart: always
    networks:
      - zum_network
    ports:
      - "6379:6379"  
networks:
  zum_network:
    driver: bridge
